<a href="https://colab.research.google.com/github/mohakhalili/Advaced-Python/blob/main/MLprerequisites-LazyProgrammer/1_TF2_0_Intro(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays vs Lists

In [ ]:
import numpy as np

In [ ]:
L = [1,2,3]

In [ ]:
A = np.array([1,2,3])

array([1, 2, 3])

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for e in A:
  print(e)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
A.append(4)

AttributeError: ignored

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4])

array([5, 6, 7])

In [ ]:
A + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
A + np.array([4,5])

ValueError: ignored

In [ ]:
2 * np.array([1,2,3])

array([2, 4, 6])

In [ ]:
2*L 

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L+L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 = []
for  e in L:
  L2.append(e+3)

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L2 = [e+3 for e in L]
L2

[4, 5, 6, 7]

In [ ]:
L**2

TypeError: ignored

In [ ]:
L2 = []
for e in L:
  L2.append(e**2)

In [ ]:
L2

[1, 4, 9, 16]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A )

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# The Dot Product


## Dot Product Definition
$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$


In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
dot = 0
for e,f in zip(a, b):
  dot += e * f
dot

11

In [ ]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a*b)

11

In [ ]:
(a*b).sum()

11

In [ ]:
np.dot(a,b )

11

In [ ]:
a @ b

11

##Another Definition
$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [ ]:
amag = np.sqrt(np.sum(a**2))
amag = np.sqrt((a*a).sum())

bmag = np.sqrt(np.sum(b**2))

In [ ]:
amag = np.linalg.norm(a)

2.23606797749979

In [ ]:
cosangle = (np.transpose(a) @ b) / (amag * bmag)
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [ ]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

# Speed Test

Speed test to measure exactly how much faster numpy is compare to regular python list in terms of the dot product

In [ ]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 63.56243623476345


# Matrices

In [ ]:
L = [[1,2] , [3,4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
A*L

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
A.dot(B.T)

ValueError: ignored

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
A.dot(np.linalg.inv(A))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
np.trace(A)

5

In [ ]:
np.diag(A)

array([1, 4])

In [ ]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [ ]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
Lam, V = np.linalg.eig(A)

In [ ]:
V[:,0] * Lam[0] == A@ V[:,0]

array([ True, False])

In [ ]:
V[:,0] * Lam[0] , A@ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [ ]:
np.allclose(V[:,0] * Lam[0] , A@ V[:,0])

True

In [ ]:
np.allclose(V @ np.diag(Lam,), A @ V)

True

# Solving Linear Systems

In [ ]:
A = np.array([[1,1],[1.5,4]])
A

array([[1. , 1. ],
       [1.5, 4. ]])

In [ ]:
b = np.array([2200,5050])
b

array([2200, 5050])

In [ ]:
x = np.linalg.inv(A).dot(b)
x

array([1500.,  700.])

In [ ]:
np.linalg.solve(A,b)

array([1500.,  700.])

# Generating Data

Uniform Distribution

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.2078271676872503

In [ ]:
np.random.random((2,3))

array([[0.8819287 , 0.19742573, 0.54247127],
       [0.49335493, 0.36627705, 0.15177463]])

Normal Distribution

In [ ]:
np.random.randn(2,3)

array([[-1.00563677, -0.22195534,  1.10551096],
       [ 1.02778984, -0.86028662, -0.37108375]])

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean()

-0.016234048125924005

In [ ]:
np.mean(R)

-0.016234048125924005

In [ ]:
R.var()

0.9945282809675782

In [ ]:
np.var(R)

0.9945282809675782

In [ ]:
R.std()

0.9972603877461383

In [ ]:
R = np.random.randn(10000, 3)
R

array([[ 0.30223007, -0.57848689,  0.41198677],
       [-0.77615083,  1.4490527 , -0.11459777],
       [-0.57114257, -0.19848289,  0.38552439],
       ...,
       [-1.88237732,  0.69116349,  1.47117465],
       [-0.46293148, -0.27228745, -1.81916011],
       [ 0.5992567 , -1.07236117,  0.94990956]])

In [ ]:
R.mean(axis=0)

array([-0.01418692, -0.01566402, -0.0133577 ])

In [ ]:
R.mean(axis=1)

array([ 0.04524331,  0.18610136, -0.12803369, ...,  0.09332027,
       -0.85145968,  0.15893503])

In [ ]:
np.cov(R).shape

(10000, 10000)

In [ ]:
np.cov(R.T)

array([[ 0.99569979, -0.01120749,  0.00548081],
       [-0.01120749,  1.00516048,  0.00766698],
       [ 0.00548081,  0.00766698,  1.02584915]])

In [ ]:
np.cov(R, rowvar=False)

array([[ 0.99569979, -0.01120749,  0.00548081],
       [-0.01120749,  1.00516048,  0.00766698],
       [ 0.00548081,  0.00766698,  1.02584915]])

In [ ]:
np.random.randint(0,10,size=[3,3])

array([[6, 8, 6],
       [3, 3, 1],
       [9, 2, 5]])

In [ ]:
np.random.choice(10,size=(3,3))

array([[1, 6, 1],
       [5, 3, 2],
       [7, 5, 1]])